services:
  svelte-ts-tailwind:
    build: 
      context: ./svelte-ts-tailwind
      dockerfile: dockerfile
    container_name: svelte-ts-tailwind
    ports:
      - 5173:5173
    volumes:
      - ./svelte-ts-tailwind/src/lib:/app/src/lib
      - ./svelte-ts-tailwind/src/routes:/app/src/routes

  nuxt-ts-tailwind:
    build: 
      context: ./nuxt-ts-tailwind
      dockerfile: dockerfile
    container_name: nuxt-ts-tailwind
    ports:
      - 3000:3000
    volumes:
      - ./nuxt-ts-tailwind/pages:/app/pages
      - ./nuxt-ts-tailwind/components:/app/components
      - ./nuxt-ts-tailwind/layouts:/app/layouts