// This file is auto-generated by @hey-api/openapi-ts

export const $UserSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'ID'
        },
        username: {
            description: 'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
            maxLength: 150,
            title: 'Username',
            type: 'string'
        },
        first_name: {
            anyOf: [
                {
                    maxLength: 150,
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    maxLength: 150,
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        }
    },
    required: ['username'],
    title: 'UserSchema',
    type: 'object'
} as const;