// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { UserViewsGetsuserResponse, UserViewsPostuserData, UserViewsPostuserResponse, UserViewsPutuserData, UserViewsPutuserResponse, UserViewsDeleteuserData, UserViewsDeleteuserResponse, UserViewsGetuserData, UserViewsGetuserResponse, UserViewsGetstestResponse, UserViewsPosttestData, UserViewsPosttestResponse, UserViewsPuttestData, UserViewsPuttestResponse, UserViewsDeletetestData, UserViewsDeletetestResponse, UserViewsGettestData, UserViewsGettestResponse } from './types.gen';

/**
 * Gets
 * @returns unknown OK
 * @throws ApiError
 */
export const userViewsGetsuser = (): CancelablePromise<UserViewsGetsuserResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/user'
}); };

/**
 * Post
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const userViewsPostuser = (data: UserViewsPostuserData): CancelablePromise<UserViewsPostuserResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/user',
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * Put
 * @param data The data for the request.
 * @param data.requset
 * @returns unknown OK
 * @throws ApiError
 */
export const userViewsPutuser = (data: UserViewsPutuserData): CancelablePromise<UserViewsPutuserResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/user',
    query: {
        requset: data.requset
    }
}); };

/**
 * Delete
 * @param data The data for the request.
 * @param data.requset
 * @returns unknown OK
 * @throws ApiError
 */
export const userViewsDeleteuser = (data: UserViewsDeleteuserData): CancelablePromise<UserViewsDeleteuserResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/api/user',
    query: {
        requset: data.requset
    }
}); };

/**
 * Get
 * @param data The data for the request.
 * @param data.uuid
 * @returns unknown OK
 * @throws ApiError
 */
export const userViewsGetuser = (data: UserViewsGetuserData): CancelablePromise<UserViewsGetuserResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/user/{uuid}',
    path: {
        uuid: data.uuid
    }
}); };

/**
 * Gets
 * @returns unknown OK
 * @throws ApiError
 */
export const userViewsGetstest = (): CancelablePromise<UserViewsGetstestResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/test'
}); };

/**
 * Post
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const userViewsPosttest = (data: UserViewsPosttestData): CancelablePromise<UserViewsPosttestResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/test',
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * Put
 * @param data The data for the request.
 * @param data.requset
 * @returns unknown OK
 * @throws ApiError
 */
export const userViewsPuttest = (data: UserViewsPuttestData): CancelablePromise<UserViewsPuttestResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/test',
    query: {
        requset: data.requset
    }
}); };

/**
 * Delete
 * @param data The data for the request.
 * @param data.requset
 * @returns unknown OK
 * @throws ApiError
 */
export const userViewsDeletetest = (data: UserViewsDeletetestData): CancelablePromise<UserViewsDeletetestResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/api/test',
    query: {
        requset: data.requset
    }
}); };

/**
 * Get
 * @param data The data for the request.
 * @param data.uuid
 * @returns unknown OK
 * @throws ApiError
 */
export const userViewsGettest = (data: UserViewsGettestData): CancelablePromise<UserViewsGettestResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/test/{uuid}',
    path: {
        uuid: data.uuid
    }
}); };