// This file is auto-generated by @hey-api/openapi-ts

export type UserSchema = {
    id?: number | null;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string | null;
    last_name?: string | null;
};

export type UserViewsGetsuserResponse = unknown;

export type UserViewsPostuserData = {
    requestBody: UserSchema;
};

export type UserViewsPostuserResponse = unknown;

export type UserViewsPutuserData = {
    requset: string;
};

export type UserViewsPutuserResponse = unknown;

export type UserViewsDeleteuserData = {
    requset: string;
};

export type UserViewsDeleteuserResponse = unknown;

export type UserViewsGetuserData = {
    uuid: string;
};

export type UserViewsGetuserResponse = unknown;

export type UserViewsGetstestResponse = unknown;

export type UserViewsPosttestData = {
    requestBody: UserSchema;
};

export type UserViewsPosttestResponse = unknown;

export type UserViewsPuttestData = {
    requset: string;
};

export type UserViewsPuttestResponse = unknown;

export type UserViewsDeletetestData = {
    requset: string;
};

export type UserViewsDeletetestResponse = unknown;

export type UserViewsGettestData = {
    uuid: string;
};

export type UserViewsGettestResponse = unknown;

export type $OpenApiTs = {
    '/api/user': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
        post: {
            req: UserViewsPostuserData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
        put: {
            req: UserViewsPutuserData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
        delete: {
            req: UserViewsDeleteuserData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/api/user/{uuid}': {
        get: {
            req: UserViewsGetuserData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/api/test': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
        post: {
            req: UserViewsPosttestData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
        put: {
            req: UserViewsPuttestData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
        delete: {
            req: UserViewsDeletetestData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/api/test/{uuid}': {
        get: {
            req: UserViewsGettestData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
};